# Generated by Django 5.1.6 on 2025-04-26 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_electionstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hudud nomi')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
            },
        ),
        migrations.CreateModel(
            name='DistrictStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_count', models.IntegerField(default=0, verbose_name='Uchastkalar soni')),
                ('registered_voters', models.IntegerField(default=0, verbose_name="Ro'yxatga olingan saylovchilar soni")),
                ('total_voters', models.IntegerField(default=0, verbose_name='Jami ovoz berganlar')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Foiz')),
                ('cancelled_ballots', models.IntegerField(default=0, verbose_name='Bekor qilingan byulletenlar')),
                ('activity_8', models.IntegerField(default=0)),
                ('activity_10', models.IntegerField(default=0)),
                ('activity_12', models.IntegerField(default=0)),
                ('activity_14', models.IntegerField(default=0)),
                ('activity_16', models.IntegerField(default=0)),
                ('activity_18', models.IntegerField(default=0)),
                ('activity_19', models.IntegerField(default=0)),
                ('activity_20', models.IntegerField(default=0)),
                ('activity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('teacher_count', models.IntegerField(default=0)),
                ('doctor_count', models.IntegerField(default=0)),
                ('engineer_count', models.IntegerField(default=0)),
                ('economist_count', models.IntegerField(default=0)),
                ('lawyer_count', models.IntegerField(default=0)),
                ('agriculture_count', models.IntegerField(default=0)),
                ('other_specialization_count', models.IntegerField(default=0)),
                ('total_specialization_count', models.IntegerField(default=0)),
                ('uzbek_count', models.IntegerField(default=0)),
                ('other_nationality_count', models.IntegerField(default=0)),
                ('higher_education_count', models.IntegerField(default=0)),
                ('secondary_education_count', models.IntegerField(default=0)),
                ('age_21_30_count', models.IntegerField(default=0)),
                ('age_31_40_count', models.IntegerField(default=0)),
                ('age_41_50_count', models.IntegerField(default=0)),
                ('age_51_60_count', models.IntegerField(default=0)),
                ('age_above_60_count', models.IntegerField(default=0)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('female_chairman_count', models.IntegerField(default=0)),
                ('female_deputy_count', models.IntegerField(default=0)),
                ('female_secretary_count', models.IntegerField(default=0)),
                ('disabled_count', models.IntegerField(default=0)),
                ('it_specialist_count', models.IntegerField(default=0)),
                ('retired_count', models.IntegerField(default=0)),
                ('russian_speakers_count', models.IntegerField(default=0)),
                ('english_speakers_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app.district')),
            ],
            options={
                'verbose_name': 'Hudud statistikasi',
                'verbose_name_plural': 'Hududlar statistikasi',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('participation_status', models.CharField(choices=[('participated', 'Avval qatnashgan'), ('not_participated', 'Avval qatnashmagan')], max_length=20, verbose_name='Qatnashish holati')),
                ('activity_field', models.CharField(choices=[('public_education', "Xalq ta'limi tizimi hodimi"), ('higher_education', "Oliy ta'lim tizimi hodimi"), ('government', 'Boshqa davlat boshqaruvlari va muassasalar xodimlari'), ('self_governance', "O'zini o'zi boshqarish organi vakillari"), ('ngo', 'Nodavlat notijorat tashkilotlar xodimlari'), ('private_sector', 'Boshqa nodavlat mavjudligi sohasi vakillari'), ('unemployed', 'Vaqtcha ishsizlar')], max_length=30, verbose_name='Faoliyat sohasi')),
                ('specialization', models.CharField(choices=[('teacher', "O'qituvchi"), ('doctor', 'Shifokor'), ('engineer', 'Muhandis'), ('economist', 'Iqtisodchi'), ('journalist', 'Jurnalist'), ('lawyer', 'Huquqshunos'), ('agriculture', "Qishloq xo'jaligi"), ('other', 'Boshqa')], max_length=20, verbose_name='Mutaxassisligi')),
                ('nationality', models.CharField(choices=[('uzbek', "O'zbek"), ('karakalpak', 'Qoraqalpoq'), ('kazakh', 'Qozoq'), ('russian', 'Rus'), ('tajik', 'Tojik'), ('korean', 'Koreys'), ('other', 'Boshqa')], max_length=20, verbose_name='Millati')),
                ('education', models.CharField(choices=[('higher', 'Oliy'), ('secondary_special', "O'rta maxsus"), ('secondary', "O'rta")], max_length=20, verbose_name="Ma'lumoti")),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Nogironligi tegishli shaxs')),
                ('is_it_specialist', models.BooleanField(default=False, verbose_name='Axborot-kommunikatsiya texnologiyalari yaratish')),
                ('is_retired', models.BooleanField(default=False, verbose_name='Nafaqadagi')),
                ('position', models.CharField(choices=[('none', "Yo'q"), ('chairman', 'Rais'), ('deputy', "Rais o'rinbosari"), ('secretary', 'Kotib')], default='none', max_length=10, verbose_name='Lavozimi')),
                ('knows_russian', models.BooleanField(default=False, verbose_name='Mukammal rus tilini biladi')),
                ('knows_english', models.BooleanField(default=False, verbose_name='Mukammal ingliz tilini biladi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatga olingan sana")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.district', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': "A'zo",
                'verbose_name_plural': "A'zolar",
            },
        ),
    ]
