# Generated by Django 5.1.6 on 2025-04-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('usk', 'UZK Azolari'), ('uchastka', 'Saylov uchastkasi'), ('vakolatli', 'Vakolatli vakil'), ('kuzatuvchi', 'Kuzatuvchi')], default='user', max_length=20),
        ),
    ]
