# Generated by Django 5.1.6 on 2025-04-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_district_districtstats_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondistrict',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precincts', to='app.district'),
        ),
    ]
